{% set version = "3.1-6" %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-bayesm
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/bayesm_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/bayesm/bayesm_{{ version }}.tar.gz
  sha256: 17d72b9cdc090845f98e7a04640380d0baef8bc23d1487c8f64dc192fdb93cb5

build:
  number: 1
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ compiler('c') }}              # [not win]
    - {{ stdlib("c") }}                # [not win]
    - {{ compiler('m2w64_c') }}        # [win]
    - {{ stdlib("m2w64_c") }}          # [win]
    - {{ compiler('cxx') }}            # [not win]
    - {{ compiler('m2w64_cxx') }}      # [win]
    - {{ posix }}filesystem        # [win]
    - {{ posix }}make
    - {{ posix }}sed               # [win]
    - {{ posix }}coreutils         # [win]
    - {{ posix }}zip               # [win]
  host:
    - libblas
    - liblapack
    - r-base
    - r-rcpp >=0.12.0
    - r-rcpparmadillo
  run:
    - r-base
    - r-rcpp >=0.12.0
    - r-rcpparmadillo

test:
  commands:
    - $R -e "library('bayesm')"           # [not win]
    - "\"%R%\" -e \"library('bayesm')\""  # [win]

about:
  home: http://www.perossi.org/home/bsm-1
  license: GPL-2.0-or-later
  summary: 'Covers many important models used in marketing and micro-econometrics applications.  The package includes: Bayes Regression (univariate or multivariate dep var), Bayes Seemingly Unrelated Regression (SUR), Binary and Ordinal Probit, Multinomial Logit (MNL) and Multinomial Probit (MNP), Multivariate Probit, Negative
    Binomial (Poisson) Regression, Multivariate Mixtures of Normals (including clustering), Dirichlet Process Prior Density Estimation with normal base, Hierarchical Linear Models with normal prior and covariates, Hierarchical Linear Models with a mixture of normals prior and covariates, Hierarchical Multinomial Logits with
    a mixture of normals prior and covariates, Hierarchical Multinomial Logits with a Dirichlet Process prior and covariates, Hierarchical Negative Binomial Regression Models, Bayesian analysis of choice-based conjoint data, Bayesian treatment of linear instrumental variables models, Analysis of Multivariate Ordinal survey
    data with scale usage heterogeneity (as in Rossi et al, JASA (01)), Bayesian Analysis of Aggregate Random Coefficient Logit Models as in BLP (see Jiang, Manchanda, Rossi 2009) For further reference, consult our book, Bayesian Statistics and Marketing by Rossi, Allenby and McCulloch (Wiley 2005) and Bayesian Non- and
    Semi-Parametric Methods and Applications (Princeton U Press 2014).'
  license_family: GPL2
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-2

extra:
  recipe-maintainers:
    - conda-forge/r
    - apcamargo

# Package: bayesm
# Version: 3.1-3
# Type: Package
# Title: Bayesian Inference for Marketing/Micro-Econometrics
# Depends: R (>= 3.2.0)
# Date: 2019-07-29
# Author: Peter Rossi <perossichi@gmail.com>
# Maintainer: Peter Rossi <perossichi@gmail.com>
# License: GPL (>= 2)
# Imports: Rcpp (>= 0.12.0), utils, stats, graphics, grDevices
# LinkingTo: Rcpp, RcppArmadillo
# Suggests: knitr, rmarkdown
# VignetteBuilder: knitr
# URL: http://www.perossi.org/home/bsm-1
# Description: Covers many important models used in marketing and micro-econometrics applications.  The package includes: Bayes Regression (univariate or multivariate dep var), Bayes Seemingly Unrelated Regression (SUR), Binary and Ordinal Probit, Multinomial Logit (MNL) and Multinomial Probit (MNP), Multivariate Probit, Negative Binomial (Poisson) Regression, Multivariate Mixtures of Normals (including clustering), Dirichlet Process Prior Density Estimation with normal base, Hierarchical Linear Models with normal prior and covariates, Hierarchical Linear Models with a mixture of normals prior and covariates, Hierarchical Multinomial Logits with a mixture of normals prior and covariates, Hierarchical Multinomial Logits with a Dirichlet Process prior and covariates, Hierarchical Negative Binomial Regression Models, Bayesian analysis of choice-based conjoint data, Bayesian treatment of linear instrumental variables models, Analysis of Multivariate Ordinal survey data with scale usage heterogeneity (as in Rossi et al, JASA (01)), Bayesian Analysis of Aggregate Random Coefficient Logit Models as in BLP (see Jiang, Manchanda, Rossi 2009) For further reference, consult our book, Bayesian Statistics and Marketing by Rossi, Allenby and McCulloch (Wiley 2005) and Bayesian Non- and Semi-Parametric Methods and Applications (Princeton U Press 2014).
# RoxygenNote: 6.0.1
# NeedsCompilation: yes
# Packaged: 2019-07-29 21:26:14 UTC; perossichi
# Repository: CRAN
# Date/Publication: 2019-07-29 22:50:02 UTC
